### ISSUE TITLE
OS3 Compatibilty

### ISSUE THREAD

**Issue by ElioS-S** [solo-fsw/opensesame4_plugin_markers#1]
When the marker plug-in is installed through pip as described in the readme, it may be accessible various OS installations. Test the effect of this when dealing with different OS versions. Test OS3 system install with OS4 via Anaconda and vice versa, and both OS3 and OS4 via Anaconda.

Also, rename this plugin so that it can live next to the OS3 version. Moving forward, make plugins OS-version specific.

Also, consider mailing Sebastian to ask if there is a location for plug-ins so that they are only reachable to the OS version they were installed for. That location should be writable w/o admin privileges.

**Comment by spruitim** [comment]
When using the pip install as described in the readme, the plugins are partly installed in their own Python folder: 
- OS3 markers plugin is installed partly, i.e. the opensesame_plugins and opensesame_extensions folders in C:\Users\%USERNAME%\AppData\Roaming\Python\share and the rest in C:\Users\%USERNAME%\AppData\Roaming\Python\Python37\site-packages
- OS4 markers plugin is installed in C:\Users\spruitim\AppData\Roaming\Python\Python311\site-packages

The OS3 markers plugin is visible in OS4 (the objects). The marker objects can however not be used, you get an error once you drag one in the task structure. When both plugins are installed, OS3 seems to use the correct plugin.

The OS4 markers plugin is not visible in OS3 (the objects) and cannot be used. When both plugins are installed, OS4 uses the correct plugin.

**Comment by spruitim** [comment]
Fixed in version 0.1.0 of OS4 plugin and version 0.2.0 of OS 3 plugin. 
- Both plugins are now installed in their own Python folders in share. 
- They have their own name: markers_os3 and markers_os4.
